# spring
spring:
  # devtools
  devtools:
    restart:
      enabled: true
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis
  redis:
    database: 1
    host: localhost
    port: 6379
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
   # multipart上传大小限制
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB


server:
  port: 8899
  servlet:
    context-path:


mybatis-plus:
  type-aliases-package: com.cvte.notesync.entity
  global-config:
    db-config:
      id-type: auto
      capital-mode: true
      table-underline: true


# jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 120000000


# 七牛配置
qiniu:
  key:
    access: kllOMCt2hi_YykRIKf5vpJLn7kyzVm0h0-MQEnOq
    secret: diQFjAae7S75MPU0wJb7-_UfBRLCAAs-TYohM4WS
  bucket:
    header: fosu-community-header
    url: http://cheader.fosuchao.com/

# 本地文件映射
file:
  path: D:/note-file/
  domain: http://127.0.0.1:8899/file/

